# MARK: Base
x-db-base: &db-base
  profiles: [ "dev" ]
  networks:
    - dev
  image: postgres:16
  restart: always
  env_file:
      - ./.env
  healthcheck:
    test:
      - CMD-SHELL
      - pg_isready -U postgres
    interval: 10s
    timeout: 5s
    retries: 5

x-app-base: &app-base
  profiles: [ "dev" ]
  networks:
    - dev
  build:
    context: ./
  restart: always
  volumes:
      - ./:/app
      - /app/.venv
  env_file:
      - ./.env

x-api-base: &api-base
  <<: *app-base
  depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    

services:
  # MARK: DB
  db:
    container_name: "db"
    <<: *db-base
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./volumes/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data

  # MARK: Redis
  redis:
    profiles: [ "dev" ]
    container_name: "redis"
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - dev

  # MARK: Celery
  celery-worker:
    container_name: "celery-worker"
    <<: *app-base
    command: celery -A tasks.celery_worker worker --loglevel=info
    healthcheck:
      test: ["CMD", "celery", "-A", "tasks.celery_worker", "inspect", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3

  celery-beat:
    container_name: "celery-beat"
    <<: *app-base
    command: celery -A tasks.celery_worker beat --loglevel=info
    healthcheck:
      test: ["CMD", "celery", "-A", "tasks.celery_worker", "inspect", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3

  # MARK: API
  admin-api:
    container_name: "admin-api"
    <<: *api-base
    command: granian --interface asgi --reload --host 0.0.0.0 --port 80 src.api.admin.api:api
    ports:
      - 80:80
    expose:
      - 80

  trader-api:
    container_name: "trader-api"
    <<: *api-base
    command: granian --interface asgi --reload --host 0.0.0.0 --port 81 src.api.trader.api:api
    ports:
      - 81:81
    expose:
      - 81

  merchant-api:
    container_name: "merchant-api"
    <<: *api-base
    command: granian --interface asgi --reload --host 0.0.0.0 --port 82 src.api.merchant.api:api
    ports:
      - 82:82
    expose:
      - 82


  support-api:
    container_name: "support-api"
    <<: *app-base
    command: granian --interface asgi --reload --host 0.0.0.0 --port 83 src.api.support.api:api
    ports:
      - 83:83
    expose:
      - 83

  # MARK: Test DB
  db-test:
    profiles: [ "test" ]
    container_name: "db-test"
    <<: *db-base
    env_file:
      - ./.env.test
    networks:
      - test

  # MARK: Test API
  api-test:
    profiles: [ "test" ]
    container_name: "api-test"
    build:
      context: ./
      args:
        ENV: test
    command: sh -c "
      alembic upgrade heads &&
      coverage run --source='.' \
      -m pytest \
      tests/integration/requisites_router_test.py \
      --dist loadscope \
      -s -r A \
      --rootdir=/app/ \
      --disable-pytest-warnings && \
      coverage html"
    env_file:
      - ./.env.test
    volumes:
      - ./:/app
      - /app/.venv
    depends_on:
      db-test:
        condition: service_healthy
    networks:
      - test

volumes:
  pgdata:
  redis-data:


networks:
  dev:
  test: