# MARK: Base
x-db-base: &db-base
  profiles: [ "dev" ]
  networks:
    - dev
  image: postgres:16
  restart: always
  env_file:
      - ./.env
  healthcheck:
    test:
      - CMD-SHELL
      - pg_isready -U postgres
    interval: 10s
    timeout: 5s
    retries: 5

x-app-base: &app-base
  profiles: [ "dev" ]
  networks:
    - dev
  build:
    context: ./
  restart: always
  volumes:
      - ./:/app
      - /app/.venv
  env_file:
      - ./.env

x-api-base: &api-base
  <<: *app-base
  depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      s3:
        condition: service_started

services:
  # MARK: DB
  db:
    container_name: "db"
    <<: *db-base
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./volumes/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data

  # MARK: Redis
  redis:
    profiles: [ "dev" ]
    container_name: "redis"
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 5
    networks:
      - dev

  # MARK: Celery
  celery-worker:
    container_name: "celery-worker"
    <<: *app-base
    command: celery -A tasks.celery_worker worker --loglevel=info
    healthcheck:
      test: ["CMD", "celery", "-A", "tasks.celery_worker", "inspect", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3

  celery-beat:
    container_name: "celery-beat"
    <<: *app-base
    command: celery -A tasks.celery_worker beat --loglevel=info
    healthcheck:
      test: ["CMD", "celery", "-A", "tasks.celery_worker", "inspect", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3

  # MARK: S3
  s3:
    profiles: [ "dev" ]
    container_name: "s3"
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001" 
    volumes:
      - s3-data:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY}
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - dev


  # MARK: API
  admin-api:
    container_name: "admin-api"
    <<: *api-base
    command: uvicorn src.api.admin.api:api --reload --host 0.0.0.0 --port 80 
    ports:
      - 80:80
    expose:
      - 80

  user-api:
    container_name: "user-api"
    <<: *api-base
    command: uvicorn src.api.user.api:api --reload --host 0.0.0.0 --port 81
    ports:
      - 81:81
    expose:
      - 81


  # MARK: Test DB
  db-test:
    profiles: [ "test" ]
    container_name: "db-test"
    <<: *db-base
    env_file:
      - ./.env.test
    networks:
      - test

  # MARK: Test API
  api-test:
    profiles: [ "test" ]
    container_name: "api-test"
    build:
      context: ./
      args:
        ENV: test
    command: sh -c "
      alembic upgrade heads &&
      coverage run --source='.' \
      -m pytest \
      --dist loadscope \
      -s -r A \
      --rootdir=/app/ \
      --disable-pytest-warnings && \
      coverage html"
    env_file:
      - ./.env.test
    volumes:
      - ./:/app
      - /app/.venv
    depends_on:
      db-test:
        condition: service_healthy
    networks:
      - test

volumes:
  pgdata:
  redis-data:
  s3-data:


networks:
  dev:
  test:
