"""initial

Revision ID: 4a144c9bb075
Revises:
Create Date: 2025-03-20 09:14:29.799823+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a144c9bb075"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID разрешения.",
        ),
        sa.Column("name", sa.String(), nullable=False, comment="Название разрешения."),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("permissions_pkey")),
        sa.UniqueConstraint("name", name=op.f("permissions_name_key")),
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Уникальный идентификатор пользователя.",
        ),
        sa.Column(
            "email",
            sa.String(),
            nullable=False,
            comment="Электронная почта пользователя.",
        ),
        sa.Column(
            "hashed_password",
            sa.String(),
            nullable=False,
            comment="Хэшированный пароль пользователя.",
        ),
        sa.Column(
            "balance", sa.Integer(), nullable=False, comment="Баланс пользователя."
        ),
        sa.Column(
            "amount_frozen",
            sa.Integer(),
            nullable=False,
            comment="Замороженные средства пользователя.",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Является ли аккаунт пользователя активным.",
        ),
        sa.Column(
            "is_2fa_enabled",
            sa.Boolean(),
            nullable=False,
            comment="Является ли 2FA включенным.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint("email", name=op.f("users_email_key")),
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("address", sa.String(length=42), nullable=False),
        sa.Column("private_key", sa.String(length=66), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("wallets_pkey")),
        sa.UniqueConstraint("address", name=op.f("wallets_address_key")),
    )
    op.create_table(
        "blockchain_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("PAY_IN", "PAY_OUT", name="typeenum"), nullable=False
        ),
        sa.Column("from_address", sa.String(length=42), nullable=True),
        sa.Column("to_address", sa.String(length=42), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", "FAILED", name="statusenum"),
            nullable=False,
        ),
        sa.Column("hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("blockchain_transactions_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("blockchain_transactions_pkey")),
    )
    op.create_table(
        "users_permissions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("users_permissions_permission_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("users_permissions_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "permission_id", name=op.f("users_permissions_pkey")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_permissions")
    op.drop_table("blockchain_transactions")
    op.drop_table("wallets")
    op.drop_table("users")
    op.drop_table("permissions")
    # ### end Alembic commands ###
