"""initial

Revision ID: 2e266b2d7abf
Revises:
Create Date: 2025-03-29 20:03:03.555723+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e266b2d7abf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="ID разрешения.",
        ),
        sa.Column("name", sa.String(), nullable=False, comment="Название разрешения."),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("permissions_pkey")),
        sa.UniqueConstraint("name", name=op.f("permissions_name_key")),
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="Уникальный идентификатор пользователя.",
        ),
        sa.Column(
            "email",
            sa.String(),
            nullable=False,
            comment="Электронная почта пользователя.",
        ),
        sa.Column(
            "hashed_password",
            sa.String(),
            nullable=False,
            comment="Хэшированный пароль пользователя.",
        ),
        sa.Column(
            "balance", sa.Integer(), nullable=False, comment="Баланс пользователя."
        ),
        sa.Column(
            "amount_frozen",
            sa.Integer(),
            nullable=False,
            comment="Замороженные средства пользователя.",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Применяется для трейдера, а именно находится ли он в работе.",
        ),
        sa.Column(
            "is_2fa_enabled",
            sa.Boolean(),
            nullable=False,
            comment="Является ли 2FA включенным.",
        ),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint("email", name=op.f("users_email_key")),
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("address", sa.String(length=42), nullable=False),
        sa.Column("private_key", sa.String(length=66), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("wallets_pkey")),
        sa.UniqueConstraint("address", name=op.f("wallets_address_key")),
    )
    op.create_table(
        "blockchain_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("PAY_IN", "PAY_OUT", name="transactiontypeenum"),
            nullable=False,
        ),
        sa.Column("from_address", sa.String(length=42), nullable=True),
        sa.Column("to_address", sa.String(length=42), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "FAILED", "SUCCESS", "DISPUTED", name="transactionstatusenum"
            ),
            nullable=False,
        ),
        sa.Column("hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("expires_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("blockchain_transactions_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("blockchain_transactions_pkey")),
    )
    op.create_table(
        "requisites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("bank_name", sa.String(), nullable=True),
        sa.Column("card_number", sa.String(), nullable=True),
        sa.Column("min_amount", sa.Integer(), nullable=True),
        sa.Column("max_amount", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("requisites_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("requisites_pkey")),
    )
    op.create_table(
        "users_permissions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("users_permissions_permission_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("users_permissions_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "permission_id", name=op.f("users_permissions_pkey")
        ),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "payment_method",
            sa.Enum("CARD", "SBP", name="transactionpaymentmethodenum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "FAILED", "SUCCESS", "DISPUTED", name="transactionstatusenum"
            ),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum("PAY_IN", "PAY_OUT", name="transactiontypeenum"),
            nullable=False,
        ),
        sa.Column("trader_id", sa.Integer(), nullable=True),
        sa.Column("requisite_id", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["users.id"], name=op.f("transactions_merchant_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["requisite_id"],
            ["requisites.id"],
            name=op.f("transactions_requisite_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["trader_id"], ["users.id"], name=op.f("transactions_trader_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("transactions_pkey")),
    )
    op.create_table(
        "disputes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("image_urls", sa.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CLOSED", name="disputestatusenum"),
            nullable=False,
        ),
        sa.Column("winner_id", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("disputes_transaction_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"], ["users.id"], name=op.f("disputes_winner_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("disputes_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("disputes")
    op.drop_table("transactions")
    op.drop_table("users_permissions")
    op.drop_table("requisites")
    op.drop_table("blockchain_transactions")
    op.drop_table("wallets")
    op.drop_table("users")
    op.drop_table("permissions")
    # ### end Alembic commands ###
